# Generated by Django 4.1.5 on 2023-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Débito"),
                            (2, "Boleto"),
                            (3, "Financiamento"),
                            (4, "Crédito"),
                            (5, "Recebimento Empréstimo"),
                            (6, "Vendas"),
                            (7, "Recebimento TED"),
                            (8, "Recebimento DOC"),
                            (9, "Aluguel"),
                        ]
                    ),
                ),
                ("date", models.IntegerField(max_length=8)),
                ("value", models.IntegerField(max_length=10)),
                ("cpf", models.IntegerField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("hour", models.IntegerField(max_length=6)),
                ("store_owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
            ],
        ),
    ]
