# Generated by Django 4.1.5 on 2023-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cpf",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="hour",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
